#! /bin/bash

if [ $# -lt 1 ]
then
    echo 'Requires at least one parameter'
    echo 'Parameter is a file that will be made executeable to all users'
    exit 1
fi


for filename in "$@"
do
   if [ -e $filename ]
   then
       chmod a+x $filename
   else
       echo $filename "is not in the system"
   fi
done
exit 0
